jwt:
  expireMinutes: 60
  expireDay: 7
  accessKey: c2VjcmV0QG5ndXllbl90aGlfdGh1X2NodWNfYWNjZXNzX3Rva2Vu
  refreshKey: c2VjcmV0QG5ndXllbl90aGlfdGh1X2NodWNfcmVmcmVzaF90b2tlbg==
api:
  version: v1
cloudinary:
  cloud_name: ${CLOUD_NAME:dqw1bfmnq}
  api_key: ${API_KEY:734735925733542}
  api_secret: ${API_SECRET:0rS6gHAGgFhyINfAYJyo9vAu644}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:DUMMY-EMAIL}
    password: ${MAIL_PASSWORD:DUMMY-PASSWORD-EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

payos:
  client-id: ${PAYOS_CLIENT_ID:ef718eee-82ca-4e25-b19a-4d4cd7063dff}
  api-key: ${PAYOS_API_KEY:b8e3dd95-04f5-49a4-97dc-85a5022798b8}
  checksum-key: ${PAYOS_CHECKSUM_KEY:6c201111eec858ee4e5e5ec9977a85559c1c32f4cdef28a33ec398c78e8a03a7}
  #Port tạm thời
  return-url: https://dd31-1-52-218-169.ngrok-free.app/api/v1/payment/success
  cancel-url: https://dd31-1-52-218-169.ngrok-free.app/api/v1/payment/cancel #Port 3001:
  #Port webhook url: #Port 8080