jwt:
  expireMinutes: 60
  expireDay: 15
  accessKey: c2VjcmV0QG5ndXllbl90aGlfdGh1X2NodWNfYWNjZXNzX3Rva2Vu
  refreshKey: c2VjcmV0QG5ndXllbl90aGlfdGh1X2NodWNfcmVmcmVzaF90b2tlbg==
  accessKeySys: aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL1RodUNodWMvYXBpLXByb2plY3RzL3JlZnMvaGVhZHMvbWFpbi9hcGktdGh1LWNodWM=
api:
  version: v1
cloudinary:
  cloud_name: ${CLOUD_NAME:dqw1bfmnq}
  api_key: ${API_KEY:734735925733542}
  api_secret: ${API_SECRET:0rS6gHAGgFhyINfAYJyo9vAu644}

spring:
  app-runner:
    isOnlySysadmin: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:DUMMY-EMAIL}
    password: ${MAIL_PASSWORD:DUMMY-PASSWORD-EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

payos:
  client-id: ${PAYOS_CLIENT_ID:fde57cbc-5ce7-414e-81dd-90a0ce21b17d}
  api-key: ${PAYOS_API_KEY:c58814cd-fec5-4bc3-b7db-f0253cea5f15}
  checksum-key: ${PAYOS_CHECKSUM_KEY:9762bfc0161008c8bb4c35e3e989013095f5301cda70f9586a96d172a57960d9}
  #Port tạm thời
  return-url: https://444f-2a09-bac5-d45d-e6-00-17-32f.ngrok-free.app/api/v1/payment/success
  cancel-url: https://444f-2a09-bac5-d45d-e6-00-17-32f.ngrok-free.app/api/v1/payment/cancel #Port 3001:
  #Port webhook url: #Port 8080