jwt:
  expireMinutes: 5
  expireDay: 15
  accessKey: c2VjcmV0QG5ndXllbl90aGlfdGh1X2NodWNfYWNjZXNzX3Rva2Vu
  refreshKey: c2VjcmV0QG5ndXllbl90aGlfdGh1X2NodWNfcmVmcmVzaF90b2tlbg==
api:
  version: v1
cloudinary:
  cloud_name: ${CLOUD_NAME:dqw1bfmnq}
  api_key: ${API_KEY:734735925733542}
  api_secret: ${API_SECRET:0rS6gHAGgFhyINfAYJyo9vAu644}

spring:
  app-runner:
    isOnlySysadmin: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:DUMMY-EMAIL}
    password: ${MAIL_PASSWORD:DUMMY-PASSWORD-EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
